config/routes.rb
Rails.application.routes.draw do
  devise_for :professionals
  devise_for :users
  root to: 'home#index'

  resources :projects, only: %i[new create show] do
    get 'search', on: :collection
    post 'close_registration', on: :member
    post 'close_project', on: :member
    get 'team', on: :member
    get 'my_projects', on: :collection
    get 'my_proposals', on: :collection
    get 'feedbacks', on: :collection
    post 'user_favorite', on: :member
    resources :proposals, shallow: true do
      post 'accept', on: :member
      post 'reject', on: :member
    end
  end
  resources :feedbacks, only: %i[new create]
  resources :professional_feedbacks, only: %i[new create]
  resources :user_feedbacks, only: %i[new create]
  resources :profiles, only: %i[new create show edit update] do
    post 'set_favorite', on: :member
    post 'unfavorite', on: :member
  end

  namespace :api do
    namespace :v1 do
      resources :projects, only: %i[index show create]
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  validates :title, :description, :skills, :max_value,
            :limit_date, :start_date, :end_date, presence: true
  validate :remote_or_presecial
  validate :limit_date_in_the_past
  validate :end_date_greater_than_start_date
  validate :start_date_in_the_past
  has_many :proposals, dependent: :nullify
  has_many :feedbacks, dependent: :nullify

  private

  def remote_or_presecial
    errors.add(:modality, 'não pode ficar em branco. Selecione uma das opções!') if modality != 0 && modality != 1
  end

  def limit_date_in_the_past
    errors.add(:limit_date, 'não pode ser em datas passadas') if !limit_date.nil? && (limit_date < Date.today)
  end

  def end_date_greater_than_start_date
    errors.add(:end_date, 'deve ser maior que a data início') if !limit_date.nil? && (start_date >= end_date)
  end

  def start_date_in_the_past
    errors.add(:start_date, 'não pode ser em datas passadas') if !limit_date.nil? && (start_date < Date.today)
  end
end

app/controllers/api/v1/projects_controller.rb
module Api
  module V1
    class ProjectsController < Api::V1::ApiController
      def index
        @projects = Project.all
        render json: @projects.as_json(except: %i[created_at updated_at])
      end

      def show
        @projects = Project.find(params[:id])
        render json: @projects.as_json(except: %i[created_at updated_at])
      end

      def create
        @project = Project.create!(project_params)
        render status: :created, json: @project
      end

      private

      def project_params
        params.require(:project).permit(:title, :description, :skills, :max_value, :limit_date,
                                        :start_date, :end_date, :modality, :user_id)
      end
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create accepted close_registration close_project]
  before_action :authenticate_professional!, only: %i[my_proposals user_favorite]
  before_action :authenticate_person, only: %i[team my_projects feedbacks]
  def new
    @project = Project.new
  end

  def create
    @project = Project.new(parametros)
    @project.user = current_user
    if @project.save
      redirect_to @project, notice: t('.success')
    else
      render :new, alert: t('.failure')
    end
  end

  def show
    if professional_signed_in?
      redirect_to new_profile_path if current_professional.pending?
      if can_see
        @project = Project.find(params[:id])
        proposals = @project.proposals.accepted
        favorito = FavoriteUser.where(user: @project.user, professional: current_professional)
        favorito.each { |fav| return @favorite = true if fav.preferred? }
        proposals.each { |prop| return @team = true if prop.professional == current_professional }
      end
    elsif can_see
      @project = Project.find(params[:id])
      return unless @project.user == current_user

      @propostas = @project.proposals.not_rated
    end
  end

  def search
    projectos = Project.where('title like ? OR description like ? OR skills like ?',
                              "%#{params[:query]}%", "%#{params[:query]}%", "%#{params[:query]}%")
    @projects = projectos.where(open_registration: true, open: true)
    @pesquisa = params[:query]
  end

  def my_proposals
    @proposals = []
    current_professional.proposals.each { |prop| @proposals << prop if prop.project.open }
  end

  def close_registration
    project = Project.find(params[:id])
    return unless project.user == current_user

    project.update_column(:open_registration, false)
    redirect_to project, notice: t('.close')
  end

  def team
    projecto = Project.find(params[:id])
    propostas = projecto.proposals.accepted
    approved = false
    propostas.each { |prop| approved = true if prop.professional == current_professional }
    if approved && professional_signed_in?
      @project = projecto
      @proposals = propostas
    elsif user_signed_in? && projecto.user == current_user
      @project = projecto
      @proposals = propostas
    end
  end

  def close_project
    project = Project.find(params[:id])
    return unless project.user == current_user

    project.update_column(:open, false)
    redirect_to feedbacks_projects_path, notice: t('.close')
  end

  def my_projects
    if user_signed_in?
      @projects = current_user.projects.where(open: true)
    elsif professional_signed_in?
      @projects = []
      current_professional.proposals.accepted.each { |prop| @projects << prop.project }
    end
  end

  def feedbacks
    if professional_signed_in?
      @proposals_projects = []
      @proposals_users = []
      current_professional.proposals.accepted.each do |prop|
        @proposals_projects << prop if current_professional.feedbacks.where(project_id: prop.project.id).blank?
        @proposals_users << prop if current_professional.user_feedbacks.where(project_id: prop.project.id).blank?
      end
      @proj_feedback = Feedback.new
      @user_feedback = UserFeedback.new
    elsif user_signed_in?
      @proposals = []
      current_user.projects.each do |proj|
        proj.proposals.accepted.each do |prop|
          return if ProfessionalFeedback.where(professional_id: prop.professional_id, user: current_user).present?

          @proposals << prop
        end
      end
      @prof_feedback = ProfessionalFeedback.new
    end
  end

  def user_favorite
    project = Project.find(params[:id])
    favorito = FavoriteUser.where(user: project.user, professional: current_professional)
    if favorito.present?
      favorito.each do |fav|
        return fav.unpreferred!, redirect_back(fallback_location: root_path) if fav.preferred?
        return fav.preferred!, redirect_back(fallback_location: root_path) if fav.unpreferred?
      end
    else
      favorite = FavoriteUser.new(user: project.user, professional: current_professional)
      redirect_to project if favorite.save
    end
  end

  private

  def parametros
    params.require(:project).permit(:title, :description, :skills, :modality, :max_value,
                                    :limit_date, :start_date, :end_date)
  end

  def aprovado
    proposals = Proposal.where(project: @project, status_proposal: 5)
    proposals.professionals
  end

  def can_see
    project = Project.find(params[:id])
    if professional_signed_in?
      proposals = project.proposals.accepted
      aprovado = false
      proposals.each { |prop| return aprovado = true if prop.professional == current_professional }
      return true if aprovado && project.open
      return true if project.open && project.open_registration
    elsif user_signed_in?
      return true if project.user == current_user && project.open
      return true if project.open && project.open_registration
    elsif project.open && project.open_registration
      true
    end
  end
end

app/views/projects/feedbacks.html.erb
<% if professional_signed_in? %>
  <h3>Aproveite para dar o feedback ao Contratador e ao Projeto</h3><br>
  <% if @proposals_projects.present?  %>
    <% @proposals_projects.each do |prop|%>
      <p>Feedback de <%= prop.project.title %>
      <div class="projectForm">
        <%= form_with model: @proj_feedback, url: feedbacks_path(project_id: prop.project.id) do |f| %></p>
          <p><%= f.label :opinion, "Feedback do Projeto: " %>
          <%= f.text_field :opinion %></p>
          <% @proj_feedback.errors.full_messages_for(:opinion).each do |erro| %>
              <%= erro %>
          <% end %>
          <p><%= f.label :nota, "Nota do Projeto: " %>
          <%= f.text_field :nota %></p>
          <% @proj_feedback.errors.full_messages_for(:nota).each do |erro| %>
              <%= erro %>
          <% end %>
          <%= f.submit 'Enviar' %></p>
        <% end %><br>
      </div>
    <% end %>
  <% end %>
  <% if @proposals_users.present?  %>
    <% @proposals_users.each do |prop|%>
      <p><%= prop.project.user.email %>
      <div class="contractorForm">
        <%= form_with model: @user_feedback, url: user_feedbacks_path(project_id: prop.project.id) do |f| %></p>
          <p><%= f.label :opinion, "Feedback do Contratador: " %>
          <%= f.text_field :opinion %></p>
          <% @user_feedback.errors.full_messages_for(:opinion).each do |erro| %>
              <%= erro %>
          <% end %>
          <p><%= f.label :grade, "Nota do Contratador: " %>
          <%= f.text_field :grade %></p>
          <% @user_feedback.errors.full_messages_for(:grade).each do |erro| %>
              <%= erro %>
          <% end %>
          <%= f.submit 'Enviar' %></p>
        <% end %><br>
      </div>
    <% end %>
  <% end %>
<% elsif user_signed_in?%>
  <h3>Aproveite para dar o feedback aos profissionais que participaram</h3><br>
  <% if @proposals.present? %>
    <% @proposals.each do |prop|%>
      <p><%= prop.professional.profile.social_name %>
      <%= form_with model: @prof_feedback, url: professional_feedbacks_path(professional_id: prop.professional.id, user_id: current_user.id) do |f| %></p>
        <p><%= f.label :opinion, "Feedback: " %>
        <%= f.text_field :opinion %></p>
        <% @prof_feedback.errors.full_messages_for(:opinion).each do |erro| %>
            <%= erro %>
        <% end %>
        <p><%= f.label :grade, "Nota: " %>
        <%= f.text_field :grade %></p>
        <% @prof_feedback.errors.full_messages_for(:grade).each do |erro| %>
            <%= erro %>
        <% end %>
        <%= f.submit 'Enviar' %></p>
      <% end %><br>
    <% end %>
  <% end %>
<% end %>

app/views/projects/my_projects.html.erb
<h3> Seus projetos </h3>
<% @projects.each do |projeto| %>
    <p><%= link_to projeto.title, projeto %></p>
    <p><%= projeto.description %></p>
<% end %> 

app/views/projects/my_proposals.html.erb
<% @proposals.each do |prop| %>
  <h3><%= prop.project.title %></h3>
  <p>Motivo: <%= prop.reason %></p>
  <p>Valor/hora: <%= number_to_currency(prop.hour_value) %></p>
  <p>Horas disponíveis por semana: <%= prop.hours_week %>
  <p>Expectativa: <%= prop.expectation %></p>
  <p><% if prop.status_proposal == 'not_rated'%>
        Status: Pendente</p>
     <% elsif prop.status_proposal == 'accepted' %>
        Status: Aceita</p>
    <% elsif prop.status_proposal == 'rejected' %>
        Status: Rejeitada</p>
    <% end %>
  <p><%= link_to 'Ver Proposta', proposal_path(prop) %></p>
<br>
<% end %>

app/views/projects/new.html.erb
<% @project.errors.any? %>

<%= form_with model: @project do |f| %>
    <p><%= f.label :title, 'Título' %>
    <%= f.text_field :title %>
    <% @project.errors.full_messages_for(:title).each do |erro| %>
        <%= erro %>
    <% end %></p>
    <p><%= f.label :description, 'Descrição' %>
    <%= f.text_field :description %>
    <% @project.errors.full_messages_for(:description).each do |erro| %>
        <%= erro %>
    <% end %></p>
    <p><%= f.label :skills, 'Habilidades desejadas' %>
    <%= f.text_field :skills %>
    <% @project.errors.full_messages_for(:skills).each do |erro| %>
        <%= erro %>
    <% end %></p>
    <p><%= f.label :modality, 'Modalidade' %>
    <%= f.select :modality, [["", ""], ["Remoto", 0], ["Presencial", 1]], selected: "" %>
    <% @project.errors.full_messages_for(:modality).each do |erro| %>
        <%= erro %>
    <% end %></p>
    <p><%= f.label :max_value, 'Valor máximo pago por hora' %>
    <%= f.number_field :max_value %>
    <% @project.errors.full_messages_for(:max_value).each do |erro| %>
        <%= erro %>
    <% end %></p>
    <p><%= f.label :limit_date, 'Data limite para candidatura' %>
    <%= f.date_field :limit_date %>
    <% @project.errors.full_messages_for(:limit_date).each do |erro| %>
        <%= erro %>
    <% end %></p>
    <p><%= f.label :start_date, 'Inicio do projeto' %>
    <%= f.date_field :start_date %>
    <% @project.errors.full_messages_for(:start_date).each do |erro| %>
        <%= erro %>
    <% end %></p>
    <p><%= f.label :end_date, 'Previsão de término' %>
    <%= f.date_field :end_date %>
    <% @project.errors.full_messages_for(:end_date).each do |erro| %>
        <%= erro %>
    <% end %></p>
    <%= f.submit 'Enviar' %>
<% end %>

app/views/projects/search.html.erb
<%= form_with url: search_projects_path, method: :get do |f| %>
    <%= f.label :query, 'Pesquisar projeto:' %>
    <%= f.text_field :query %>
    <%= f.submit 'Buscar' %>
<%end%>

<h4> Resultado da Pesquisa: <%= @pesquisa %></h4>

<% @projects.each do |projeto| %>
    <b><%= link_to projeto.title, project_path(projeto) %></b>
    <p>Descrição: <%= projeto.description %></p>
    <p>Habilidade desejadas: <%= projeto.skills %></p>
<% end %>

app/views/projects/show.html.erb
<h3><%= @project.title %></h3>
<p>Projeto de <%= @project.user.email  %></p>
<% if @favorite %>
  <p>Contratador marcado como favorito</p>
<% end %>
<p>Descrição: <%= @project.description  %></p>
<p>Habilidades desejadas: <%= @project.skills %></p>
<p>Valor max por hora: <%= number_to_currency(@project.max_value) %></p>
<p>Data limite para candidatura: <%= I18n.l(@project.limit_date) %></p>
<p>Inicio do projeto: <%= I18n.l(@project.start_date) %></p>
<p>Previsão de término: <%=I18n.l(@project.end_date) %></p>
<br>
<% if professional_signed_in? %>
<p><%= link_to 'Marcar', user_favorite_project_path(@project.id), method: :post %> <%= @project.user.email  %> como Favorito </p>
  <% if @team %>
    <%= link_to 'Time do Projeto', team_project_path %>    
  <% end %>    
    <h3>Deseja se candidatar para este projeto?</h3>
    <p>Por favor preencha o formulário informando o que te motiva a participar do projeto,
    valor por hora de trabalho, quantas horas por semana tem disponibilidade e qual a 
    sua expectativa para este projeto.</p>

    <p><%= link_to 'Candidatar para projeto', new_project_proposal_path(@project,@user) %><p>
<% elsif user_signed_in? && @project.user == current_user %>
        <%= link_to 'Time do Projeto', team_project_path(@project.id) %>
        <%= link_to 'Encerrar inscrições', close_registration_project_path(@project.id), method: :post %>
        <%= link_to 'Encerrar Projeto', close_project_project_path(@project.id), method: :post %>
    <% @propostas.each do |prop| %>
        <h4>Proposta de <%= link_to prop.professional.profile.social_name, profile_path(prop.professional.profile) %></h4>
        <p>Motivo: <%= prop.reason %></p>
        <p>Valor/hora: <%= number_to_currency(prop.hour_value) %></p>
        <p>Horas disponíveis por semana: <%= prop.hours_week %>
        <p>Expectativa: <%= prop.expectation %></p>
        <p><% if prop.status_proposal == 'not_rated'%>
              Status: Pendente</p>
           <% elsif prop.status_proposal == 'accepted' %>
              Status: Aceita</p>
          <% elsif prop.status_proposal == 'rejected' %>
              Status: Rejeitada</p>
          <% end %>
        <%= link_to 'Aceitar proposta', accept_proposal_path(prop.id), method: :post %>
        <%= form_with url: reject_proposal_path(prop.id), method: :post do |f| %>
            <%= f.label :justify, "Feedback" %>
            <%= f.text_field :justify %>
            <%= f.submit "Rejeitar proposta" %>
        <% end %>
    <% end %>
<% end %>

app/views/projects/team.html.erb
<h2><%= @project.title %></h2>
<%= @openn %>
<h4>Lista dos aprovados para o projeto <%= @project.title %></h4>
<% @proposals.each do |prop| %>
    <p><%= prop.professional.profile.social_name %><p>
    <p><%= prop.professional.profile.formation %><p>
    <p><%= prop.reason %><p>
    <% if user_signed_in? && @project.user == current_user %>
      <p><%= link_to "Proposta de #{prop.professional.profile.social_name}", prop%></p><br>
    <% end %><br>
<% end %>