config/routes.rb
Rails.application.routes.draw do
  devise_for :professionals
  devise_for :users
  root to: 'home#index'

  resources :projects, only: %i[new create show] do
    get 'search', on: :collection
    post 'close_registration', on: :member
    post 'close_project', on: :member
    get 'team', on: :member
    get 'my_projects', on: :collection
    get 'my_proposals', on: :collection
    get 'feedbacks', on: :collection
    post 'user_favorite', on: :member
    resources :proposals, shallow: true do
      post 'accept', on: :member
      post 'reject', on: :member
    end
  end
  resources :feedbacks, only: %i[new create]
  resources :professional_feedbacks, only: %i[new create]
  resources :user_feedbacks, only: %i[new create]
  resources :profiles, only: %i[new create show edit update] do
    post 'set_favorite', on: :member
    post 'unfavorite', on: :member
  end

  namespace :api do
    namespace :v1 do
      resources :projects, only: %i[index show create]
    end
  end
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  belongs_to :project
  belongs_to :professional
  enum status_proposal: { not_rated: 0, accepted: 5, rejected: 10 }
  before_create :generate_code
  validates :code, uniqueness: true
  validates :reason, :hour_value, :hours_week, :expectation, presence: true
  validates :hour_value, :hours_week, numericality: true

  private

  def generate_code
    self.code = SecureRandom.alphanumeric(8).upcase
    generate_code if Proposal.exists?(code: code)
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_action :authenticate_professional!, only: %i[new create destroy]
  before_action :authenticate_user!, only: %i[accept reject]
  before_action :authenticate_person, only: [:show]

  def new
    @proposal = Proposal.new
  end

  def create
    @proposal = current_professional.proposals.new(proposal_params)
    @proposal.project = Project.find(params[:project_id])
    @proposta = current_professional.proposals.find_by project_id: params[:project_id]
    if @proposta.present?
      redirect_to @proposta, notice: 'Você já tem uma proposta para este projeto!'
    elsif @proposal.save
      ProposalMailer.with(proposal: @proposal).notify_new_proposal.deliver_now
      redirect_to @proposal, notice: 'Proposta enviada com sucesso!'
    else
      render :new
    end
  end

  def show
    prop = Proposal.find(params[:id])
    project = prop.project
    if user_signed_in?
      return @proposal = prop if current_user == project.user
    elsif professional_signed_in?
      return @proposal = prop if current_professional == prop.professional
    end
  end

  def edit
    @proposal = Proposal.find(params[:id])
  end

  def update
    @proposal = Proposal.find(params[:id])
    if @proposal.update(proposal_params)
      redirect_to @proposal, notice: t('.success')
    else
      render :edit, alert: t('.failure')
    end
  end

  def accept
    project = Proposal.find(params[:id]).project
    return unless current_user == project.user

    @proposal = Proposal.find(params[:id])
    @proposal.accepted!
    redirect_to @proposal.project, notice: 'Proposta aceita com sucesso!'
  end

  def reject
    project = Proposal.find(params[:id]).project
    return unless current_user == project.user

    @proposal = Proposal.find(params[:id])
    @proposal.rejected!
    @proposal.update!({ justify: params[:justify] })
    redirect_to @proposal.project, notice: 'Proposta rejeitada com sucesso!'
  end

  def destroy
    prop = Proposal.find(params[:id])
    return unless current_professional == prop.professional

    prop.destroy
    redirect_to root_path, notice: 'Proposta cancelada com sucesso!'
  end

  private

  def proposal_params
    params.require(:proposal).permit(:reason, :hour_value,
                                     :hours_week, :expectation, :justify, :code)
  end
end

app/views/proposals/_proposal_form.html.erb
<%= form_with model: @proposal do |f| %>
  <p><%= f.label :reason, 'Motivo:' %>
  <%= f.text_field :reason %>
  <% @proposal.errors.full_messages_for(:reason).each do |erro| %>
      <%= erro %>
  <% end %></p>
  <p><%= f.label :hour_value, 'Valor/hora:' %>
  <%= f.number_field :hour_value %>
  <% @proposal.errors.full_messages_for(:hour_value).each do |erro| %>
      <%= erro %>
  <% end %></p>
  <p><%= f.label :hours_week, 'Horas disponíveis por semana:' %>
  <%= f.number_field :hours_week, step: 1, min: 1 %>
  <% @proposal.errors.full_messages_for(:hours_week).each do |erro| %>
      <%= erro %>
  <% end %></p>
  <p><%= f.label :expectation, 'Expectativa:' %>
  <%= f.text_field :expectation %>
  <% @proposal.errors.full_messages_for(:expectation).each do |erro| %>
      <%= erro %>
  <% end %></p>
  <%= f.submit 'Enviar proposta' %>
<% end %>

app/views/proposals/edit.html.erb
<%= render 'proposals/proposal_form', object: @proposal %>

app/views/proposals/new.html.erb
<%= form_with model: @proposal, url: project_proposals_path do |f| %>
    <p><%= f.label :reason, 'Motivo:' %>
    <%= f.text_field :reason %>
    <% @proposal.errors.full_messages_for(:reason).each do |erro| %>
        <%= erro %>
    <% end %></p>
    <p><%= f.label :hour_value, 'Valor/hora:' %>
    <%= f.number_field :hour_value %>
    <% @proposal.errors.full_messages_for(:hour_value).each do |erro| %>
        <%= erro %>
    <% end %></p>
    <p><%= f.label :hours_week, 'Horas disponíveis por semana:' %>
    <%= f.number_field :hours_week, step: 1, min: 1 %>
    <% @proposal.errors.full_messages_for(:hours_week).each do |erro| %>
        <%= erro %>
    <% end %></p>
    <p><%= f.label :expectation, 'Expectativa:' %>
    <%= f.text_field :expectation %>
    <% @proposal.errors.full_messages_for(:expectation).each do |erro| %>
        <%= erro %>
    <% end %></p>
    <%= f.submit 'Enviar proposta' %>
<% end %>

app/views/proposals/show.html.erb
<h3> Proposta para atuar no projeto <%= @proposal.project.title %></h3>
<p>Proposta de <%= @proposal.professional.profile.social_name %></p>
<p>Motivo: <%= @proposal.reason%></p>
<p>Valor/hora: <%=number_to_currency(@proposal.hour_value)%></p>
<p>Horas disponíveis: <%= @proposal.hours_week%></p>
<p><%= @proposal.expectation%></p>
<p><%= link_to 'Ver Projeto', @proposal.project %>
<% if user_signed_in? %>
  <%= link_to 'Ver Perfil', @proposal.professional.profile %></p>
<% elsif professional_signed_in? && @proposal.professional == current_professional %>
  <%= link_to 'Editar Proposta', edit_proposal_path %>
  <%= link_to 'Cancelar Proposta', proposal_path(@proposal), method: :delete %></p>
<% end %>