config/routes.rb
Rails.application.routes.draw do
  devise_for :professionals
  devise_for :users
  root to: 'home#index'

  resources :projects, only: %i[new create show] do
    get 'search', on: :collection
    post 'close_registration', on: :member
    post 'close_project', on: :member
    get 'team', on: :member
    get 'my_projects', on: :collection
    get 'my_proposals', on: :collection
    get 'feedbacks', on: :collection
    post 'user_favorite', on: :member
    resources :proposals, shallow: true do
      post 'accept', on: :member
      post 'reject', on: :member
    end
  end
  resources :feedbacks, only: %i[new create]
  resources :professional_feedbacks, only: %i[new create]
  resources :user_feedbacks, only: %i[new create]
  resources :profiles, only: %i[new create show edit update] do
    post 'set_favorite', on: :member
    post 'unfavorite', on: :member
  end

  namespace :api do
    namespace :v1 do
      resources :projects, only: %i[index show create]
    end
  end
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark">
  <ul class="navbar-nav">
    <li><div class="dropdown show">
      <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Acesso
      </a>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
        <a class="dropdown-item" href="/users/sign_in">Entrar como contratador</a>
        <a class="dropdown-item" href="/professionals/sign_in">Entrar como profissional</a>
      </div>
    </div></li>
    <li><%= link_to 'Home', root_path, class: "navbar-brand text-light" %></li>
  </ul>
  <ul class="navbar-nav ml-auto">
    <li>
      <%= form_with url: search_projects_path, method: :get do |f| %>
        <label class="searchLabel"><%= f.text_field :query%></label>
        <%= f.submit 'Buscar' %>
      <%end%>
    </li>
  </ul>
</nav>

app/views/layouts/_professional_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark justify-content-center">
  <div class="d-flex flex-row">
    <ul class="navbar-nav">
      <li class="nav-item "><%= link_to 'Home', root_path, class: "nav-link text-light" %></li>
      <li class="nav-item "><%= link_to 'Meu perfil', profile_path(current_professional), class: "nav-link text-light" %></li>
      <li class="nav-item "><%= link_to 'Minhas Propostas', my_proposals_projects_path, class: "nav-link text-light" %></li>
      <li class="nav-item "><%= link_to 'Feedbacks', feedbacks_projects_path, class: "nav-link text-light" %></li>
      <li class="nav-item "><%= link_to 'Meus Projetos', my_projects_projects_path, class: "nav-link text-light" %></li>
    </ul>
  </div>
  <div>
    <%= form_with url: search_projects_path, method: :get do |f| %>
      <label class="searchLabel"><%= f.text_field :query%></label>
      <%= f.submit 'Buscar' %>
    <%end%>
  </div>
</nav>

app/views/layouts/_user_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark">
  <ul class="navbar-nav">
    <li class="nav-item"><%= link_to 'Home', root_path, class: "navbar-brand text-light" %></li>
    <li class="nav-item"><%= link_to 'Meus Projetos', my_projects_projects_path, class: "navbar-brand text-light" %></li>
    <li class="nav-item"><%= link_to 'Cadastrar Projeto', new_project_path, class: "navbar-brand text-light" %></li>
    <li class="nav-item"><%= link_to 'Feedbacks', feedbacks_projects_path, class: "navbar-brand text-light" %></li>
  </ul>
  <ul class="navbar-nav ml-auto">
    <li>
      <%= form_with url: search_projects_path, method: :get do |f| %>
        <label class="searchLabel"><%= f.text_field :query%></label>
        <%= f.submit 'Buscar' %>
      <%end%>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Freelas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% if user_signed_in? %>
        <p><%= current_user.email %>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete %></p>
        <%= image_tag("logo_freelas.png", height:'250', width:'100%') %><br>
        <%= render 'layouts/user_navbar'%>
      <% elsif professional_signed_in? %>
        <p><%= current_professional.email %>
        <%= link_to 'Logout', destroy_professional_session_path, method: :delete %></p>
        <%= image_tag("logo_freelas.png", height:'250', width:'100%') %><br>
        <%= render 'layouts/professional_navbar'%>
      <% else %>
        <%= image_tag("logo_freelas.png", height:'250', width:'100%') %><br>
        <%= render 'layouts/navbar'%>
      <% end %>
      <%= render 'shared/flash_messages'%><br>
        <%= yield %>
    </div>  
  </body>
</html>